stages:
- build
- test
- publish

cmake-no-git:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build gcc-c++
    - git submodule update --init --recursive
    - ./packaging/make-srpm.sh
    - yum-builddep -y build/SRPMS/*
    - rm -rf .git build
    - mkdir build
    - cd build
    - cmake3 ..

cmake-tarball:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build gcc-c++
    - git submodule update --init --recursive
    - ./packaging/make-srpm.sh
    - yum-builddep -y build/SRPMS/*
    - packaging/make-dist.sh
    - cd build
    - tar xf davix-*.tar.gz
    - cd davix-*/
    - mkdir build && cd build
    - cmake3 ..

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

slc6:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  script:
    - ci/fedora/packages.sh
    - yum install -y python-argparse tar
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-29:
  stage: build
  image: fedora:29
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-30:
  stage: build
  image: fedora:30
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

ubuntu-disco:
  stage: build
  image: ubuntu:disco
  script:
    - ci/debian/packages.sh
    - apt install -y python2
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,ddeb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ci/debian/packages.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

docs-generate:
  stage: build
  image: fedora:29
  script:
    - dnf install -y git python3-sphinx python3-pip gcc-c++ rpm-build dnf-plugins-core python2 python3-breathe make
    - packaging/make-docs.sh
    - mv build/doc/build/html docs
  artifacts:
    paths:
    - docs

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  script:
    - yum install -y cc7/RPMS/*.rpm
    - davix-unit-tests

slc6-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  dependencies:
    - slc6
  script:
    - yum install -y slc6/RPMS/*.rpm
    - davix-unit-tests

fedora-29-test:
  stage: test
  image: fedora:29
  dependencies:
    - fedora-29
  script:
    - dnf install -y fedora-29/RPMS/*.rpm
    - davix-unit-tests

fedora-30-test:
  stage: test
  image: fedora:30
  dependencies:
    - fedora-30
  script:
    - dnf install -y fedora-30/RPMS/*.rpm
    - davix-unit-tests

docs:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - docs-generate
  script:
    - yum install -y sssd-client sudo
    - chown -R stci docs
    - SNAPSHOT=$(date +%s)
    - TARGET="/eos/project/d/davix/www/docs/${CI_COMMIT_REF_NAME}"
    - STAGING_AREA="$TARGET-${SNAPSHOT}"
    - sudo -u stci -H cp -r docs "$STAGING_AREA"
    - sudo -u stci -H ci/replace-directory.sh "$STAGING_AREA" "$TARGET"
  tags:
    - docker-cc7
  retry: 2
  only:
    - branches@dmc/davix
    - tags@dmc/davix

rpms:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
    - slc6
  script:
    - yum install -y python sssd-client sudo createrepo
    - for platform in cc7 slc6; do sudo -u stci -H packaging/repo-manager.py --action add --base /eos/project/s/storage-ci/www/davix --ref ${CI_COMMIT_REF_NAME} --packages ${platform}/RPMS/* ${platform}/SRPMS/* ; done
    - echo "$DAVIXCI_PW" | kinit davixci
    - cp cc7/RPMS/* cc7/SRPMS/* /eos/project-d/d/dmc/www/repos/testing/el7/x86_64
    - packaging/update-repo.sh /eos/project-d/d/dmc/www/repos/testing/el7/x86_64
    - cp slc6/RPMS/* slc6/SRPMS/* /eos/project-d/d/dmc/www/repos/testing/el6/x86_64
    - packaging/update-repo.sh /eos/project-d/d/dmc/www/repos/testing/el6/x86_64
  tags:
    - docker-cc7
  retry: 2
  only:
    - branches@dmc/davix
    - tags@dmc/davix
